title: Java Docs
description: Documentation, class notes, & project instructions for AP Computer Science: Java Programming.
theme: just-the-docs

url: https://javadocs.coderina.dev

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
